source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
#inhibit_all_warnings!

def common
	pod 'WeexSDK'
	pod 'WeexPluginLoader'
    # pod 'RMStore', '~> 0.7'
    pod 'RMStore', :git => 'https://github.com/sirnacnud/RMStore.git'
    pod 'RMStore/NSUserDefaultsPersistence'
    #    pod 'RMStore/AppReceiptVerificator'
#    pod 'VerifyStoreReceipt', '1.0.1'
#    pod 'OpenSSL'
end

target 'WeexPluginInapp' do
    common
end

