name: Publish package to the Maven Central Repository
on:
  release:
    types: [published]
jobs:
  publish:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          gradle-version: 2.3.3
      - name: Publish library
        working-directory: android/library
        env:
          bintrayUser: ${{ secrets.BINTRAY_USER }}
          bintrayApiKey: ${{ secrets.BINTRAY_APIKEY }}
        run: gradle bintrayUpload 
