# This is a basic workflow to help you get started with Actions

name: Maven Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Gradle
        run: gradle build 
      - name: Upload package to Bintray
        uses: bpicode/github-action-upload-bintray@master
        with:
          file: android/library/build/outputs/aar/library-debug.aar
          api_user: weex
          api_key: ${{ secrets.gpg_private_key }} # An API key can be obtained from the user profile page.
          gpg_passphrase: ${{ secrets.gpg_passphrase }} # Optional, for this to work Bintray requires a GPG public/private keypair configured for the repository owner (individual or organization).
          repository_user: weex
          repository: weex_android
          package: de.eyzmedia.plugin.weexinapp
          version: '1.0'
          publish: 1
      
